FROM node:22-bullseye@sha256:d7ecd44a5983a6647565509527498f1051ba409cfe847d2ab514fd67c2d67a2a

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get clean

WORKDIR /workspace

COPY package.json yarn.lock tsconfig.json .eslintrc.js ./
COPY src ./src
RUN yarn
COPY test ./test
COPY .buildkite/scripts/test.sh .buildkite/scripts/test.sh
